### ISSUE TITLE
Nome progetto fuorviante

### ISSUE THREAD

**Issue by anaselli** [OpenGenova/Install-WelcomeRigenera-linux-x64#1]
@enri-ge io chiamerei questo progetto se, come mi sembra di aver capito si tratta dell'installer per welcome message, in un altro modo, con questo nome sembra che installi Rigenera linux.
Cosa ne pensi?

**Comment by enri-ge** [comment]
@anaselli Ok, ti è possibile rinominarlo? Scegli il nome che ritieni meno fuorviante, io non ho badato molto a questo aspetto :-)

**Comment by anaselli** [comment]
ok. Tieni presente che una volta rinominato il progetto devi rifare il clone o [cambiare url](https://help.github.com/articles/changing-a-remote-s-url/)

**Comment by enri-ge** [comment]
Si ok, rinomina. Io poi rifaccio tutto!

**Comment by anaselli** [comment]
rinominato come **Install-WelcomeRigenera-linux-x64**. Se pernsi che installer sia meglio vai sotto il progetto e Settings poi cambia il nome nuovamente.
